title: Carta de Amor
email: andresmanuel.p@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Carta de Amor para Mar√≠a Roque
url: "https://code-andres.github.io"

# Build settings
theme: jekyll-theme-merlot